# gcr.io/${PROJECT_ID}/simple-api:${SHORT_SHA}
steps:
  # Build Image
  - name: 'gcr.io/cloud-builders/docker'
    args:  [ 'build', '-t', 'gcr.io/${PROJECT_ID}/simple-api:${SHORT_SHA}', '.' ]

  # Push to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/simple-api:${SHORT_SHA}']

  # Deploy to GKE
  - name: 'ubuntu'
    args:
      - sed 
      - -i 
      - "s,<PROJECT_ID>,$PROJECT_ID,g"
      - k8s/deployment.yaml

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s
      - --image=gcr.io/${PROJECT_ID}/simple-api:${SHORT_SHA}
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
