# gcr.io/cloudkite-interviews-306021/thoth-ky/simple-api:c17c630d5cba5a2b9f28886e01bb75b5ae6b58f70bbbaa54c75cf99d8d32427e
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:  [ 'build', '-t', 'gcr.io/cloudkite-interviews-306021/thoth-ky/simple-api:${SHORT_SHA}', '.' ]
images: ['gcr.io/cloudkite-interviews-306021/thoth-ky/simple-api:${SHORT_SHA}']
