apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: simple-api
  namespace: default
  labels:
    app: simple-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: web-app
          image: gcr.io/<PROJECT_ID>/simple-api
          ports:
            - containerPort: 8000
          command: ["uvicorn", "main:app","--host", "0.0.0.0", "--log-level", "info"]