
apiVersion: v1
kind: Service

metadata:
  name: web-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: simple-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
