---
# tasks file for cluster-setup
- name: create a cluster
  google.cloud.gcp_container_cluster:
    name: prod-cluster
    initial_node_count: 1
    location: us-central1-f
    auth_kind: serviceaccount
    service_account_file: "{{ service_account_file}}" # set in ENV GCP_SERVICE_ACCOUNT_FILE
    project: "{{ project_name }}"
    node_config:
      oauth_scopes: [
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
        "https://www.googleapis.com/auth/devstorage.read_only"
      ]
      machine_type: e2-medium
    state: present
  register: cluster

- name: create a node pool
  google.cloud.gcp_container_node_pool:
    name: web-pool
    initial_node_count: 1
    cluster: "{{ cluster }}"
    location: us-central1-f
    project: "{{ project_name }}"
    auth_kind: serviceaccount
    service_account_file: "{{ service_account_file}}"
    config:
      oauth_scopes: [
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
        "https://www.googleapis.com/auth/devstorage.read_only"
      ]
      machine_type: e2-medium
    state: present
